// Code generated by Wire protocol buffer compiler, do not edit.
// Source: olegmoney.UserService in user_service.proto
package olegmoney

import com.squareup.wire.GrpcCall
import com.squareup.wire.GrpcClient
import com.squareup.wire.GrpcMethod

public class GrpcUserServiceClient(
  private val client: GrpcClient,
) : UserServiceClient {
  override fun SignUp(): GrpcCall<UserRequest, UserResponse> = client.newCall(GrpcMethod(
      path = "/olegmoney.UserService/SignUp",
      requestAdapter = UserRequest.ADAPTER,
      responseAdapter = UserResponse.ADAPTER
  ))

  override fun SignIn(): GrpcCall<UserRequest, UserResponseLogin> = client.newCall(GrpcMethod(
      path = "/olegmoney.UserService/SignIn",
      requestAdapter = UserRequest.ADAPTER,
      responseAdapter = UserResponseLogin.ADAPTER
  ))
}
