// Code generated by Wire protocol buffer compiler, do not edit.
// Source: olegmoney.UserResponse in user.proto
package olegmoney

import android.os.Parcelable
import com.squareup.wire.AndroidMessage
import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.sanitize
import kotlin.Any
import kotlin.Boolean
import kotlin.Int
import kotlin.Long
import kotlin.String
import okio.ByteString

public class UserResponse(
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 0,
  )
  @JvmField
  public val name: String = "",
  @field:WireField(
    tag = 2,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 1,
  )
  @JvmField
  public val email: String = "",
  unknownFields: ByteString = ByteString.EMPTY,
) : AndroidMessage<UserResponse, UserResponse.Builder>(ADAPTER, unknownFields) {
  override fun newBuilder(): Builder {
    val builder = Builder()
    builder.name = name
    builder.email = email
    builder.addUnknownFields(unknownFields)
    return builder
  }

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is UserResponse) return false
    if (unknownFields != other.unknownFields) return false
    if (name != other.name) return false
    if (email != other.email) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + name.hashCode()
      result = result * 37 + email.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """name=${sanitize(name)}"""
    result += """email=${sanitize(email)}"""
    return result.joinToString(prefix = "UserResponse{", separator = ", ", postfix = "}")
  }

  public fun copy(
    name: String = this.name,
    email: String = this.email,
    unknownFields: ByteString = this.unknownFields,
  ): UserResponse = UserResponse(name, email, unknownFields)

  public class Builder : Message.Builder<UserResponse, Builder>() {
    @JvmField
    public var name: String = ""

    @JvmField
    public var email: String = ""

    public fun name(name: String): Builder {
      this.name = name
      return this
    }

    public fun email(email: String): Builder {
      this.email = email
      return this
    }

    override fun build(): UserResponse = UserResponse(
      name = name,
      email = email,
      unknownFields = buildUnknownFields()
    )
  }

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<UserResponse> = object : ProtoAdapter<UserResponse>(
      FieldEncoding.LENGTH_DELIMITED, 
      UserResponse::class, 
      "type.googleapis.com/olegmoney.UserResponse", 
      PROTO_3, 
      null, 
      "user.proto"
    ) {
      override fun encodedSize(`value`: UserResponse): Int {
        var size = value.unknownFields.size
        if (value.name != "") size += ProtoAdapter.STRING.encodedSizeWithTag(1, value.name)
        if (value.email != "") size += ProtoAdapter.STRING.encodedSizeWithTag(2, value.email)
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: UserResponse) {
        if (value.name != "") ProtoAdapter.STRING.encodeWithTag(writer, 1, value.name)
        if (value.email != "") ProtoAdapter.STRING.encodeWithTag(writer, 2, value.email)
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: UserResponse) {
        writer.writeBytes(value.unknownFields)
        if (value.email != "") ProtoAdapter.STRING.encodeWithTag(writer, 2, value.email)
        if (value.name != "") ProtoAdapter.STRING.encodeWithTag(writer, 1, value.name)
      }

      override fun decode(reader: ProtoReader): UserResponse {
        var name: String = ""
        var email: String = ""
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> name = ProtoAdapter.STRING.decode(reader)
            2 -> email = ProtoAdapter.STRING.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return UserResponse(
          name = name,
          email = email,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: UserResponse): UserResponse = value.copy(
        unknownFields = ByteString.EMPTY
      )
    }

    @JvmField
    public val CREATOR: Parcelable.Creator<UserResponse> = AndroidMessage.newCreator(ADAPTER)

    private const val serialVersionUID: Long = 0L
  }
}
